apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: app1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
      repoURL: https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      targetRevision: 4.10.0
      helm:
        values: |
          controller:
            replicaCount: 2
            service:
              type: LoadBalancer
            ingressClassResource:
              name: "nginx"
            metrics:
              enabled: true
          controller:
            service:
              type: NodePort

    